<form>
    <table>
        <tbody>
            <tr>
                <td>Логин:</td>
                <td>
                    <input name="login"
                           type="text"
                           value="" />
                </td>
            </tr>

            <tr>
                <td>Пароль:</td>
                <td>
                    <input name="password"
                           type="password"
                           value="" />
                </td>
            </tr>

            <tr>
                <td colspan="2">
                    <input type="submit" value="Войти" />
                </td>
            </tr>

            <tr>
                <td colspan="2"><span class="js-error-message"></span></td>
            </tr>
        </tbody>
    </table>
</form>
