<fieldset>
    <legend>Регистрация пользователя</legend>
    <p>
        <label for="login">Логин</label>
        <input ng-model="user.login" id="login" type="text" />
    </p>
    <p>
        <label for="password">Пароль</label>
        <input ng-model="user.password" id="password" type="password" />
    </p>
    <p>
        <label for="password1">Повтор пароля</label>
        <input ng-model="user.password1" id="password1" type="password" />
    </p>
    <p>
        <label for="email">e-mail</label>
        <input ng-model="user.email" id="email" type="text" />
    </p>
    <p>
        <label for="info">Инфо</label>
        <textarea ng-model="user.info" id="info"></textarea>
    </p>
    <p>
        <label for="site">Сайт</label>
        <input ng-model="user.site" id="site" type="text" />
    </p>
    <p class="text-error">
        {{message}}
    </p>
    <p>
        <button ng-click="register()" class="btn">Зарегистрироваться</button>
    </p>
</fieldset>
