<?php if (null != $this->error): ?>
<p class="text-error">
    <?php echo $this->error ?>
</p>
<?php endif ?>

<?php if (true == $this->registered): ?>
Вы успешно зарегистрированы, теперь можете зайти на сайт и создать персонажа.
<?php else: ?>
<form action="/registration" method="post">
    <fieldset>
        <legend>Регистрация пользователя</legend>
        <p>
            <label for="login">Логин</label>
            <input id="login"
                   type="text"
                   name="login"
                   value="<?php echo $this->_registry->request->post->login ?>">
        </p>
        <p>
            <label for="password">Пароль</label>
            <input id="password"
                   type="password"
                   name="password">
        </p>
        <p>
            <label for="password1">Повтор пароля</label>
            <input id="password1"
                   type="password"
                   name="password1">
        </p>
        <p>
            <label for="email">e-mail</label>
            <input id="email"
                   type="text"
                   name="email"
                   value="<?php echo $this->_registry->request->post->email ?>">
        </p>
        <p>
            <label for="info">
                Инфо
            </label>
            <textarea id="info"
                      name="info"><?php echo ( !empty($_POST['info']) ) ? $_POST['info'] : '' ?></textarea>
        </p>
        <p>
            <label for="site">Сайт</label>
            <input id="site"
                   type="text"
                   name="site"
                   value="<?php echo $this->_registry->request->post->site ?>">
        </p>
        <p>
            <input type="submit"
                   class="btn"
                   value="Зарегистрироваться">
        </p>
    </fieldset>
</form>
<?php endif ?>
