<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <title>ismd-game<?php echo $this->_title; ?></title>
        <link rel="stylesheet" type="text/css" href="/css/main.css" />
        <link rel="stylesheet" type="text/css" href="/css/custom-theme/jquery-ui-1.8.20.custom.css" />
        <script type="text/javascript" src="/js/jquery.js"></script>
        <script type="text/javascript" src="/js/jquery-ui.js"></script>
        <script type="text/javascript" src="/js/auth.js"></script>
        <?php foreach ($this->_css as $link): ?>
        <link rel="stylesheet" type="text/css" href="/css/<?php echo $link; ?>.css" />
        <?php endforeach ?>
        <?php foreach ($this->_js as $link): ?>
        <script type="text/javascript" src="/js/<?php echo $link; ?>.js"></script>
        <?php endforeach ?>
    </head>
    <body>
        <div id="left-panel">
            <div id="logo">
                Лого
            </div>

            <?php if (null != $this->_registry->session->user): ?>
            <div id="auth">
                Добро пожаловать, <?php echo $this->_registry->session->user->login ?><br />
                <a href="/auth/logout">Выход</a>
            </div>

            <div id="character">
                <a id="select-character" href="#">Выбрать персонажа</a>
            </div>
            <?php else: ?>
            <div id="auth">
                <a href="#" id="auth-button">Войти в игру</a><br />
                <br />
                <a href="/registration">Регистрация</a><br />
                <a href="#">Забыли пароль</a>

                <!-- Форма аутентификации -->
                <div id="auth-form" title="Вход в игру">
                    <form>
                        <fieldset>
                            <label for="login">Логин</label>
                            <input type="text" name="login" id="login" class="text ui-widget-content ui-corner-all" />
                            <label for="password">Пароль</label>
                            <input type="password" name="password" id="password" value="" class="text ui-widget-content ui-corner-all" />
                        </fieldset>
                    </form>
                </div>
            </div>
            <?php endif ?>

            <!-- Форма выбора персонажа -->
            <div id="characters-list">
                Ваши персонажи:
                <ul id="characters-list">
                </ul>
            </div>

            <?php if ( isset($this->_session->character) ): ?>
            <div id="character">
                Персонаж:<br />
                <?php echo $this->_session->character->name ?> - <?php echo $this->_session->character->level ?> уровень<br />
                hp: <span id="hp"><?php echo $this->_session->character->hp ?></span>/<?php echo $this->_session->character->maxHp ?><br />
                Сила: <?php echo $this->_session->character->strength ?><br />
                Ловкость: <?php echo $this->_session->character->dexterity ?><br />
                Выносливость: <?php echo $this->_session->character->endurance ?><br /><br />
                <a href="/world/inventory">Инвентарь</a>
            </div>
            <?php endif ?>
        </div>

        <div id="top-menu">
            <div class="top-menu-item">
                <a href="#">Форум</a>
            </div>
            <div class="top-menu-item">
                <a href="/world">Мир</a>
            </div>
            <div class="top-menu-item">
                <a href="/">Главная</a>
            </div>
        </div>

        <div id="content">
