<!doctype html>
<html lang="ru" ng-app="main">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>ismd-game</title>

        <link href="/css/bootstrap.css" rel="stylesheet" media="screen">
        <link href="/css/bootstrap-responsive.css" rel="stylesheet">
        <link href="/css/main.css" rel="stylesheet" media="screen">
        <link href="/css/world.css" rel="stylesheet" media="screen">

        <script src="/js/lib/jquery.js"></script>
        <script src="/js/lib/bootstrap.js"></script>
        <script src="/js/lib/angular.js"></script>
        <script src="/js/lib/angular-resource.js"></script>
        <script src="/js/app/init.js"></script>

        <script src="/js/app/controllers/UserCtrl.js"></script>
        <script src="/js/app/controllers/CharacterCtrl.js"></script>
        <script src="/js/app/controllers/MapCtrl.js"></script>

        <script src="/js/app/services/UserServices.js"></script>
        <script src="/js/app/services/CharacterServices.js"></script>
        <script src="/js/app/services/MapServices.js"></script>

        <?php if (null != $this->user): ?>
        <script>
        window.user            = <?php echo json_encode($this->user->toArray()) ?>;
        window.user.characters = <?php echo json_encode($this->userCharacters) ?>;
        </script>
        <?php endif ?>

        <?php if (null != $this->character): ?>
        <script>
        window.character = <?php echo json_encode($this->character->toArray()) ?>;
        </script>
        <?php endif ?>
    </head>
    <body>
        <div ng-controller="CharacterCtrl" class="container">
            <div class="row">
                <!-- Sidebar -->
                <div class="span2">
                    <div class="sidebar-nav-fixed with-borders">
                        <div ng-controller="UserCtrl" ng-switch on="user" class="row">
                            <div ng-switch-when="undefined" class="span2">
                                <button class="left-pannel-button btn btn-primary"
                                   href="#auth-form"
                                   role="button"
                                   data-toggle="modal"
                                   target="_self">Войти в игру</button>
                                <hr>
                                <a class="left-panel-button btn" href="/registration">
                                    Регистрация
                                </a>
                                <br>
                                <a class="left-panel-button btn" href="#">
                                    Забыли пароль
                                </a>
                            </div>

                            <div ng-switch-default class="span2">
                                Добро пожаловать, {{user.login}}

                                <hr>

                                <!-- Инфа о персонаже -->
                                <div ng-controller="CharacterCtrl" ng-switch on="character" class="row">
                                    <div ng-switch-when="undefined" class="span2">
                                        <a id="select-character-open"
                                           href="#select-character"
                                           role="button"
                                           data-toggle="modal"
                                           class="btn"
                                           target="_self">Выбрать персонажа</a>
                                    </div>

                                    <div ng-switch-default class="span2">
                                        <h3 id="character-name">
                                            {{character.name}}
                                        </h3>

                                        <table>
                                            <tr>
                                                <td>
                                                    Уровень:
                                                </td>
                                                <td>
                                                    {{character.level}}
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    Опыт:
                                                </td>
                                                <td>
                                                    {{character.experience}}
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    Жизнь:
                                                </td>
                                                <td>
                                                    <span id="hp">{{character.hp}}</span>/{{character.maxHp}}<br>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    Сила:
                                                </td>
                                                <td>
                                                    {{character.strength}}
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    Ловкость:
                                                </td>
                                                <td>
                                                    {{character.dexterity}}
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    Выносливость:
                                                </td>
                                                <td>
                                                    {{character.endurance}}
                                                </td>
                                            </tr>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- Форма аутентификации -->
                    <div ng-controller="UserCtrl" id="auth-form" class="modal hide fade" tabindex="-1" role="dialog" aria-hidden="true">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                            <h3>Вход в игру</h3>
                        </div>
                        <div class="modal-body">
                            <form>
                                <label for="username">Логин</label>
                                <input ng-model="username" type="text" placeholder="Введите логин">
                                <label for="password">Пароль</label>
                                <input ng-model="password" type="password" placeholder="Введите пароль">
                            </form>
                        </div>
                        <div class="modal-footer">
                            <button ng-click="login(username, password)" id="login-button" class="btn btn-primary">Войти</button>
                        </div>
                    </div>

                    <!-- Форма выбора персонажа -->
                    <div ng-controller="UserCtrl" id="select-character" class="modal hide fade" role="dialog">
                        <div class="modal-header">
                            <button type="button"
                                    class="close"
                                    data-dismiss="modal"
                                    aria-hidden="true">&times;</button>

                            <h3>Выберите персонажа</h3>
                        </div>
                        <div class="modal-body">
                            <img ng-class="{hide: user.characters != undefined}" class="loading" src="/img/loading.gif">

                            <table ng-class="{hide: user.characters == undefined}" class="table table-hover">
                                <thead>
                                    <tr>
                                        <th>Имя</th>
                                        <th>Уровень</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr ng-repeat="character in user.characters">
                                        <td ng-click="setCharacter(character.id)">
                                            <img ng-src="/img/world/characters/{{character.image}}">
                                            {{character.name}}
                                        </td>
                                        <td>{{character.level}}</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>

                <!-- Navbar -->
                <div class="span10">
                    <div class="navbar">
                        <div class="navbar-inner">
                            <div class="container">
                                <ul class="nav">
                                    <li>
                                        <a href="/">
                                            <i class="icon-home"></i>
                                            Главная
                                        </a>
                                    </li>

                                    <li ng-controller="CharacterCtrl" ng-class="{hide: character == undefined}" class="dropdown">
                                        <a href="#" class="dropdown-toggle"
                                           data-toggle="dropdown" data-target="#">
                                            Игра
                                            <b class="caret"></b>
                                        </a>

                                        <ul class="dropdown-menu">
                                            <li>
                                                <a href="/world">
                                                    Мир
                                                </a>
                                            </li>
                                            <li>
                                                <a href="/world/inventory">
                                                    Инвентарь
                                                </a>
                                            </li>
                                        </ul>
                                    </li>

                                    <li>
                                        <a href="database">
                                            База знаний
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            Форум
                                        </a>
                                    </li>
                                </ul>

                                <ul class="nav pull-right">
                                    <li ng-controller="UserCtrl" ng-class="{hide: user == undefined}" class="dropdown">
                                        <a href="#" class="dropdown-toggle"
                                           data-toggle="dropdown" data-target="#">
                                            Настройки
                                            <b class="caret"></b>
                                        </a>

                                        <ul class="dropdown-menu">
                                            <li>
                                                <a id="select-character-open"
                                                   href="#select-character"
                                                   role="button"
                                                   data-toggle="modal"
                                                   target="_self">Выбрать персонажа</a>
                                            </li>

                                            <li>
                                                <a href="/auth/logout">
                                                    Выход
                                                </a>
                                            </li>
                                        </ul>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>

                    <div class="row-fluid">
                        <div class="span12">
                            <div ng-view></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>
