<div class="row-fluid">
    <!-- Левый верхний угол -->
    <div class="span7">
        <!-- Содержимое клетки -->
        <div ng-controller="CellContentCtrl" id="cell-content" class="span12">
            <div ng-repeat="item in content">
                <div ng-click="selectItem(item.type, item.id)"
                     ng-class="{selected: item.id == selectedItem.id && item.type == selectedItem.type}"
                     class="{{item.type}}"
                     data-id="{{item.id}}"
                     title="{{item.name}}">
                    <img ng-src="{{item.image}}" />
                </div>
            </div>
        </div>

        <div class="row-fluid">
            <!-- Действия -->
            <div id="main-panel" class="span6 with-borders">
                <table>
                    <tbody>
                        <tr>
                            <td><button id="kill" class="btn btn-small btn-danger disabled">Убить</button></td>
                            <td><button id="talk" class="btn btn-small btn-success disabled">Общаться</button></td>
                            <td><button id="pick-up" class="btn btn-small btn-warning disabled">Подобрать</button></td>
                        </tr>
                        <tr>
                            <td><button id="look" class="btn btn-small btn-info disabled">Осмотреть</button></td>
                            <td>&nbsp;</td>
                            <td>&nbsp;</td>
                        </tr>
                    </tbody>
                </table>
            </div>

            <!-- Информация о локации -->
            <div id="location-info" class="span6 with-borders">
                <table class="table table-condensed">
                    <tbody>
                        <tr>
                            <td>Зона</td>
                            <td>Древний лес</td>
                        </tr>
                        <tr>
                            <td>Локация</td>
                            <td>Около старого дуба</td>
                        </tr>
                        <tr>
                            <td>Координаты</td>
                            <td>{{character.x}}x{{character.y}}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <div ng-controller="MapCtrl" id="top-right" class="span5">
        <!-- Карта -->
        <div class="span12">
            <canvas id="map" width="350" height="250">Обновите браузер</canvas>

            <div id="right-of-map">
                <i class="icon-star"></i><br />
                <i class="icon-tag"></i><br />
                <i class="icon-pencil"></i><br />
                <i class="icon-eye-open"></i><br />
                <i class="icon-wrench"></i><br />
                <i class="icon-fullscreen"></i>
            </div>
        </div>

        <!-- Кнопки перемещения -->
        <div class="row-fluid">
            <div id="move-buttons" class="span12">
                <button ng-click="map.moveTop()" id="move-top"><i class="icon-arrow-up"></i></button><br />
                <button ng-click="map.moveLeft()" id="move-left"><i class="icon-arrow-left"></i></button>
                <button ng-click="map.moveRight()" id="move-right"><i class="icon-arrow-right"></i></button><br />
                <button ng-click="map.moveBottom()" id="move-bottom"><i class="icon-arrow-down"></i></button>
            </div>
        </div>
    </div>
</div>

<!-- Чат -->
<div class="row-fluid">
    <div id="chat" class="span12 with-borders">
        Здесь будет чат
    </div>
</div>
