<div class="col-md-3">
    <a href="javascript:void(0)"
       class="js-add btn btn-primary btn-block">Добавить</a>
    <br />

    <div class="js-mobs-list list-group"></div>
</div>

<div class="js-mob-info"></div>

<script id="mobs-template" type="x-tmpl-mustache">
{{#mobs}}
<a href="javascript:void(0)"
   class="js-mob list-group-item"
   data-index="{{attributes.index}}">
    <span class="badge"
          title="Максимальное количество в мире">{{attributes.maxInWorld}}</span>

    {{attributes.name}}
</a>
{{/mobs}}
</script>

<script id="mob-info-template" type="x-tmpl-mustache">
<div class="col-md-2">
    <a href="javascript:void(0)"
       class="js-edit btn btn-primary btn-block">Редактировать</a>
    <br />

    <p>
        id: {{mob.attributes.id}}
    </p>
    <p>
        Уровень: {{mob.attributes.level}}
    </p>
    <p>
        Минимальный урон: {{mob.attributes.minDamage}}
    </p>
    <p>
        Максимальный урон: {{mob.attributes.maxDamage}}
    </p>
    <p>
        Максимум жизней: {{mob.attributes.maxHp}}
    </p>
    <p>
        Опыт: {{mob.attributes.experience}}
    </p>
</div>

<div class="col-md-7">
    <img src="<?= $this->siteUrl; ?>/pictures/mobs_resized/120x120_{{mob.attributes.image}}" />
</div>
</script>

<script id="mob-edit-template" type="x-tmpl-mustache">
<div class="col-md-2">
    <a href="javascript:void(0)"
       class="js-back btn btn-default btn-block">Назад</a>
    <br />

    <p>
        id: {{mob.attributes.id}}
    </p>
    <p>
        Имя:
        <input type="text"
               name="name"
               value="{{mob.attributes.name}}" />
    </p>
    <p>
        Уровень:
        <input type="text"
               name="level"
               value="{{mob.attributes.level}}" />
    </p>
    <p>
        Минимальный урон:
        <input type="text"
               name="minDamage"
               value="{{mob.attributes.minDamage}}" />
    </p>
    <p>
        Максимальный урон:
        <input type="text"
               name="maxDamage"
               value="{{mob.attributes.maxDamage}}" />
    </p>
    <p>
        Максимум жизней:
        <input type="text"
               name="maxHp"
               value="{{mob.attributes.maxHp}}" />
    </p>
    <p>
        Опыт:
        <input type="text"
               name="experience"
               value="{{mob.attributes.experience}}" />
    </p>
    <p>
        Максимум в мире:
        <input type="text"
               name="maxInWorld"
               value="{{mob.attributes.maxInWorld}}" />
    </p>

    <a href="javascript:void(0)"
       class="js-save btn btn-primary btn-block">Сохранить</a>
</div>

<div class="col-md-7">
    <img class="js-image"
         src="<?= $this->siteUrl; ?>/pictures/mobs_resized/120x120_{{mob.attributes.image}}" />
    <br />

    <input type="file"
           name="image" />
</div>
</script>

<script id="mob-add-template" type="x-tmpl-mustache">
<div class="col-md-2">
    <a href="javascript:void(0)"
       class="js-back btn btn-default btn-block">Назад</a>
    <br />

    <p>
        Имя:
        <input type="text"
               name="name" />
    </p>
    <p>
        Уровень:
        <input type="text"
               name="level" />
    </p>
    <p>
        Минимальный урон:
        <input type="text"
               name="minDamage" />
    </p>
    <p>
        Максимальный урон:
        <input type="text"
               name="maxDamage" />
    </p>
    <p>
        Максимум жизней:
        <input type="text"
               name="maxHp" />
    </p>
    <p>
        Опыт:
        <input type="text"
               name="experience" />
    </p>
    <p>
        Максимум в мире:
        <input type="text"
               name="maxInWorld" />
    </p>

    <a href="javascript:void(0)"
       class="js-save btn btn-primary btn-block">Создать</a>
</div>

<div class="col-md-7">
    <img class="js-image"
         src="<?= $this->siteUrl; ?>/pictures/mobs_resized/120x120_" />
    <br />

    <input type="file"
           name="image" />
</div>
</script>
