<script>
window.siteUrl = '<?= $this->siteUrl; ?>';
window.vicinity = <?= json_encode($this->vicinity); ?>;
</script>

<div class="col-md-3">
    <a href="javascript:void(0)"
       class="js-add btn btn-success btn-block">Добавить</a>
    <br />

    <div class="js-mobs-list list-group"></div>
</div>

<div class="col-md-4">
    <div class="js-mob-info row"></div>
</div>

<div class="col-md-5">
    <div class="js-map">
        <div class="map">
            <canvas width="<?= 30 * count($this->vicinity[0]); ?>"
                    height="<?= 30 * count($this->vicinity); ?>"></canvas>
        </div>

        <div class="row">
            <div class="col-md-6">
                Выбранные клетки:
                <div class="js-selected-cells"></div>
            </div>

            <div class="col-md-6">
                <a href="javascript:void(0)"
                   class="js-save-available-cells btn btn-primary">Сохранить</a>
                <br />

                <span class="js-available-cells-saved available-cells-saved">Сохранено!</span>
            </div>
        </div>
    </div>
</div>

<script id="mobs-template" type="x-tmpl-mustache">
{{#mobs}}
<a href="javascript:void(0)"
   class="js-mob list-group-item"
   data-index="{{attributes.index}}">
    <span class="badge"
          title="Максимальное количество в мире">{{attributes.maxInWorld}}</span>

    {{attributes.name}}
</a>
{{/mobs}}
</script>

<script id="map-cells-template" type="x-tmpl-mustache">
<ul>
    {{#cells}}
    <li>Зона: {{idLayout}}, x: {{x}}, y: {{y}}</li>
    {{/cells}}
</ul>
</script>

<script id="mob-info-template" type="x-tmpl-mustache">
<div class="col-md-7">
    <a href="javascript:void(0)"
       class="js-edit btn btn-primary btn-block">Редактировать</a>
    <br />

    <p>
        id: {{mob.attributes.id}}
    </p>
    <p>
        Уровень: {{mob.attributes.level}}
    </p>
    <p>
        Минимальный урон: {{mob.attributes.minDamage}}
    </p>
    <p>
        Максимальный урон: {{mob.attributes.maxDamage}}
    </p>
    <p>
        Максимум жизней: {{mob.attributes.maxHp}}
    </p>
    <p>
        Опыт: {{mob.attributes.experience}}
    </p>

    <a href="javascript:void(0)"
       class="js-delete btn btn-danger btn-block">Удалить</a>
</div>

<div class="col-md-5">
    <img src="<?= $this->siteUrl; ?>/pictures/mobs_resized/120x120_{{mob.attributes.image}}" />
</div>
</script>

<script id="mob-edit-template" type="x-tmpl-mustache">
<div class="col-md-7">
    <a href="javascript:void(0)"
       class="js-back btn btn-default btn-block">Назад</a>
    <br />

    <p>
        id: {{mob.attributes.id}}
    </p>
    <p>
        Имя:
        <input type="text"
               name="name"
               value="{{mob.attributes.name}}" />
    </p>
    <p>
        Уровень:
        <input type="text"
               name="level"
               value="{{mob.attributes.level}}" />
    </p>
    <p>
        Минимальный урон:
        <input type="text"
               name="minDamage"
               value="{{mob.attributes.minDamage}}" />
    </p>
    <p>
        Максимальный урон:
        <input type="text"
               name="maxDamage"
               value="{{mob.attributes.maxDamage}}" />
    </p>
    <p>
        Максимум жизней:
        <input type="text"
               name="maxHp"
               value="{{mob.attributes.maxHp}}" />
    </p>
    <p>
        Опыт:
        <input type="text"
               name="experience"
               value="{{mob.attributes.experience}}" />
    </p>
    <p>
        Максимум в мире:
        <input type="text"
               name="maxInWorld"
               value="{{mob.attributes.maxInWorld}}" />
    </p>

    <a href="javascript:void(0)"
       class="js-save btn btn-primary btn-block">Сохранить</a>
</div>

<div class="col-md-5">
    <img class="js-image"
         src="<?= $this->siteUrl; ?>/pictures/mobs_resized/120x120_{{mob.attributes.image}}" />
    <br /><br />

    <label class="btn btn-default">
        Загрузить
        <input type="file" name="image" />
    </label>
</div>
</script>

<script id="mob-add-template" type="x-tmpl-mustache">
<div class="col-md-7">
    <a href="javascript:void(0)"
       class="js-back btn btn-default btn-block">Назад</a>
    <br />

    <p>
        Имя:
        <input type="text"
               name="name" />
    </p>
    <p>
        Уровень:
        <input type="text"
               name="level" />
    </p>
    <p>
        Минимальный урон:
        <input type="text"
               name="minDamage" />
    </p>
    <p>
        Максимальный урон:
        <input type="text"
               name="maxDamage" />
    </p>
    <p>
        Максимум жизней:
        <input type="text"
               name="maxHp" />
    </p>
    <p>
        Опыт:
        <input type="text"
               name="experience" />
    </p>
    <p>
        Максимум в мире:
        <input type="text"
               name="maxInWorld" />
    </p>

    <a href="javascript:void(0)"
       class="js-save btn btn-primary btn-block">Создать</a>
</div>

<div class="col-md-5">
    <img class="js-image"
         src="<?= $this->siteUrl; ?>/pictures/mobs_resized/120x120_" />
    <br /><br />

    <label class="btn btn-default">
        Загрузить
        <input type="file" name="image" />
    </label>
</div>
</script>
