<div id="auth-form" class="modal fade" role="dialog" tabindex="-1">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button"
                        class="close"
                        data-dismiss="modal"
                        aria-label="Close"><span aria-hidden="true">&times;</span></button>

                <h3>Вход в игру</h3>
            </div>

            <div class="modal-body">
                <form>
                    <div class="form-group">
                        <label for="username">Логин</label>
                        <input ng-model="username"
                               id="username"
                               class="form-control"
                               enter="login(username, password)"
                               type="text"
                               placeholder="Введите логин" />
                    </div>

                    <div class="form-group">
                        <label for="password">Пароль</label>
                        <input ng-model="password"
                               id="password"
                               class="form-control"
                               enter="login(username, password)"
                               type="password"
                               placeholder="Введите пароль" />
                    </div>
                </form>

                <p class="text-danger">{{loginMessage}}</p>
            </div>

            <div class="modal-footer">
                <button ng-click="login(username, password)"
                        ng-class="{disabled: loginInProcess}"
                        class="btn btn-primary">Войти</button>
            </div>
        </div>
    </div>
</div>
