<!doctype html>
<html lang="ru">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Game Admin</title>

        <link href="/css/style.css" rel="stylesheet" media="screen" />
        <script src="/js/app.js"></script>

        <script>
        window.ws = {
            host: '<?= $this->ws['host'] ?>',
            port: <?= $this->ws['port'] ?>
        };
        </script>
    </head>

    <body class="page-<?= $this->_registry->router->getController(); ?>-<?= $this->_registry->router->getAction(); ?>">
        <nav class="navbar navbar-default navbar-fixed-top">
            <div class="container-fluid">
                <div class="collapse navbar-collapse"
                     id="main-menu">
                    <ul class="nav navbar-nav">
                        <? $controller = $this->_registry->router->getController(); ?>

                        <li<?= 'Index' == $controller ? ' class="active"' : ''; ?>><a href="/">Главная</a></li>
                        <li<?= 'Map' == $controller ? ' class="active"' : ''; ?>><a href="/map">Карта</a></li>
                        <li<?= 'Mobs' == $controller ? ' class="active"' : ''; ?>><a href="/mobs">Мобы</a></li>
                        <li<?= 'Npcs' == $controller ? ' class="active"' : ''; ?>><a href="/npcs">NPC</a></li>
                    </ul>

                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="/auth/logout">Выйти</a></li>
                    </ul>
                </div>
            </div>
        </nav>

        <div class="container">
            <div class="row">
                <?= $this->content(); ?>
            </div>
        </div>
    </body>
</html>
