<!DOCTYPE html>
<html lang="ru">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>ismd-game<?php echo $this->getTitle() ?></title>
        <script data-main="/js/main" src="/js/require.js"></script>
        <link href="/css/custom-theme/jquery-ui-1.8.20.custom.css" rel="stylesheet" media="screen">
        <link href="/css/bootstrap.css" rel="stylesheet" media="screen">
        <link href="/css/bootstrap-responsive.css" rel="stylesheet">
        <link href="/css/main.css" rel="stylesheet" media="screen">
        <?php foreach ($this->getCss() as $link): ?>
        <link href="/css/<?php echo $link ?>.css" rel="stylesheet" type="text/css">
        <?php endforeach ?>
        <?php foreach ($this->getJs() as $js): ?>
        <?php $attributes = array() ?>
        <?php foreach ($js['attributes'] as $key => $value): ?>
        <?php $attributes[] = $key . '="' . $value . '"' ?>
        <?php endforeach ?>
        <script<?php if (count($attributes) > 0) echo ' ' . implode(' ', $attributes) ?> src="/js/<?php echo $js['link'] ?>.js"></script>
        <?php endforeach ?>
    </head>
    <body>
        <div class="container">
            <div class="row">
                <!-- Sidebar -->
                <div class="span2">
                    <div class="sidebar-nav-fixed with-borders">
                        <?php if (null == $this->_registry->session->user): ?>
                        <div class="row">
                            <div class="span2">
                                <a id="auth-button-open" href="#auth-form" role="button" class="btn" data-toggle="modal">
                                    Войти в игру
                                </a>
                                <hr>
                                <a id="registration-button" class="btn" href="/registration">
                                    Регистрация
                                </a>
                                <br>
                                <a id="forgot-password-button" class="btn" href="#">
                                    Забыли пароль
                                </a>
                            </div>
                        </div>
                        <?php else: ?>
                        <div class="row">
                            <div class="span2">
                                Добро пожаловать, <?php echo $this->_registry->session->user->login ?>
                            </div>
                        </div>

                        <hr>

                        <?php if (null != $this->_registry->session->character): ?>
                        <!-- Инфа о персонаже -->
                        <div class="row">
                            <div class="span2">
                                <h3 id="character-name">
                                    <?php echo $this->_registry->session->character->name ?>
                                </h3>
                                
                                <table>
                                    <tr>
                                        <td>
                                            Уровень:
                                        </td>
                                        <td>
                                            <?php echo $this->_registry->session->character->level ?>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            Опыт:
                                        </td>
                                        <td>
                                            <?php echo $this->_registry->session->character->experience ?>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            Жизнь:
                                        </td>
                                        <td>
                                            <span id="hp"><?php echo $this->_registry->session->character->hp ?></span>/<?php echo $this->_registry->session->character->maxHp ?><br>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            Сила:
                                        </td>
                                        <td>
                                            <?php echo $this->_registry->session->character->strength ?>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            Ловкость:
                                        </td>
                                        <td>
                                            <?php echo $this->_registry->session->character->dexterity ?>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            Выносливость:
                                        </td>
                                        <td>
                                            <?php echo $this->_registry->session->character->endurance ?>
                                        </td>
                                    </tr>
                                </table>
                            </div>
                        </div>
                        <?php else: ?>
                        <div class="row">
                            <div class="span2">
                                <a id="select-character" href="#" class="btn">
                                    Выбрать персонажа
                                </a>
                            </div>
                        </div>
                        <?php endif ?>
                        <?php endif ?>
                    </div>
                </div>

                <!-- Navbar -->
                <div class="span10">
                    <div class="navbar">
                        <div class="navbar-inner">
                            <div class="container">
                                <ul class="nav">
                                    <?php if ('index' == $this->_registry->router->getController()): ?>
                                    <li class="active">
                                    <?php else: ?>
                                    <li>
                                    <?php endif ?>
                                        <a href="/">
                                            <i class="icon-home"></i>
                                            Главная
                                        </a>
                                    </li>
                                    <?php if (null != $this->_registry->session->character): ?>
                                    <?php if ('world' == $this->_registry->router->getController()): ?>
                                    <li class="dropdown active">
                                    <?php else: ?>
                                    <li class="dropdown">
                                        <?php endif ?>
                                        <a href="#" class="dropdown-toggle"
                                           data-toggle="dropdown" data-target="#">
                                            Игра
                                            <b class="caret"></b>
                                        </a>
                                        
                                        <ul class="dropdown-menu">
                                            <li>
                                                <a href="/world">
                                                    Мир
                                                </a>
                                            </li>
                                            <li>
                                                <a href="/world/inventory">
                                                    Инвентарь
                                                </a>
                                            </li>
                                        </ul>
                                    </li>
                                    <?php endif ?>
                                    <li>
                                        <a href="#">
                                            База знаний
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            Форум
                                        </a>
                                    </li>
                                </ul>
                                <?php if (null != $this->_registry->session->user): ?>
                                <ul class="nav pull-right">
                                    <li class="dropdown">
                                        <a href="#" class="dropdown-toggle"
                                           data-toggle="dropdown" data-target="#">
                                            Настройки
                                            <b class="caret"></b>
                                        </a>

                                        <ul class="dropdown-menu">
                                            <li>
                                                <a id="select-character" href="#">
                                                    Выбрать персонажа
                                                </a>
                                            </li>

                                            <li>
                                                <a href="/auth/logout">
                                                    Выход
                                                </a>
                                            </li>
                                        </ul>
                                    </li>
                                </ul>
                                <?php endif ?>
                            </div>
                        </div>
                    </div>

                    <div class="row-fluid">
                        <div class="span12">
                            <?php echo $this->content() ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
        <?php if (null == $this->_registry->session->user): ?>
        <!-- Форма аутентификации -->
        <div id="auth-form" class="modal hide fade" role="dialog">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h3>Вход в игру</h3>
            </div>
            <div class="modal-body">
                <form>
                    <label for="username">Логин</label>
                    <input id="username" type="text">
                    <label for="password">Пароль</label>
                    <input id="password" type="password">
                </form>
            </div>
            <div class="modal-footer">
                <a id="auth-button-login" class="btn btn-primary">
                    Войти
                </a>
            </div>
        </div>
        <?php endif ?>

        <!-- Форма выбора персонажа -->
        <div id="select-character" class="modal hide fade" role="dialog">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h3>Выберите персонажа</h3>
            </div>
            <div class="modal-body">
                <ul id="characters-list" />
            </div>
        </div>
    </body>
</html>
