<!DOCTYPE html>
<html lang="ru">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>ismd-game<?php echo $this->getTitle() ?></title>
        <link href="/css/custom-theme/jquery-ui-1.8.20.custom.css" rel="stylesheet" media="screen">
        <link href="/css/bootstrap.css" rel="stylesheet" media="screen">
        <link href="/css/bootstrap-responsive.css" rel="stylesheet">
        <link href="/css/main.css" rel="stylesheet" media="screen">
        <script src="/js/jquery.js"></script>
        <script src="/js/jquery-ui.js"></script>
        <script src="/js/bootstrap.js"></script>
        <script src="/js/auth.js"></script>
        <?php foreach ($this->getCss() as $link): ?>
        <link href="/css/<?php echo $link ?>.css" rel="stylesheet" type="text/css">
        <?php endforeach ?>
        <?php /*foreach ($this->getJs() as $link): ?>
        <script src="/js/<?php echo $link ?>.js"></script>
        <?php endforeach*/ ?>
    </head>
    <body>
        <div class="container">
            <div class="row">
                <!-- Sidebar -->
                <div class="span2">
                    <div class="sidebar-nav-fixed with-borders">
                        <?php if (null == $this->_registry->session->user): ?>
                        <div class="row">
                            <div class="span2">
                                <a href="#" id="auth-button" class="btn">Войти в игру</a><br>
                                <br>
                                <a href="/registration" class="btn">Регистрация</a><br>
                                <a href="#" class="btn">Забыли пароль</a>

                                <!-- Форма аутентификации -->
                                <div id="auth-form" class="hide" title="Вход в игру">
                                    <form>
                                        <fieldset>
                                            <label for="login">Логин</label>
                                            <input type="text" name="login" id="login" class="text ui-widget-content ui-corner-all">
                                            <label for="password">Пароль</label>
                                            <input type="password" name="password" id="password" value="" class="text ui-widget-content ui-corner-all">
                                        </fieldset>
                                    </form>
                                </div>
                            </div>
                        </div>
                        <?php else: ?>
                        <div class="row">
                            <div class="span2">
                                Добро пожаловать, <?php echo $this->_registry->session->user->login ?>
                            </div>
                        </div>

                        <div class="row">
                            <div class="span2">
                                <a id="select-character" href="#" class="btn">
                                    Выбрать персонажа
                                </a>
                            </div>
                        </div>
                        
                        <hr>

                        <?php if (null != $this->_registry->session->character): ?>
                        <!-- Инфа о персонаже -->
                        <div class="row">
                            <div class="span2">
                                <h3 id="character-name">
                                    <?php echo $this->_registry->session->character->name ?>
                                </h3>
                                
                                <table>
                                    <tr>
                                        <td>
                                            Уровень:
                                        </td>
                                        <td>
                                            <?php echo $this->_registry->session->character->level ?>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            Опыт:
                                        </td>
                                        <td>
                                            <?php echo $this->_registry->session->character->experience ?>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            Жизнь:
                                        </td>
                                        <td>
                                            <span id="hp"><?php echo $this->_registry->session->character->hp ?></span>/<?php echo $this->_registry->session->character->maxHp ?><br>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            Сила:
                                        </td>
                                        <td>
                                            <?php echo $this->_registry->session->character->strength ?>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            Ловкость:
                                        </td>
                                        <td>
                                            <?php echo $this->_registry->session->character->dexterity ?>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            Выносливость:
                                        </td>
                                        <td>
                                            <?php echo $this->_registry->session->character->endurance ?>
                                        </td>
                                    </tr>
                                </table>
                            </div>
                        </div>
                        <?php endif ?>
                        <?php endif ?>
                    </div>
                </div>

                <!-- Header -->
                <div class="span10">
                    <div class="navbar">
                        <div class="navbar-inner">
                            <ul class="nav">
                                <?php if ('index' == $this->_registry->router->getController()): ?>
                                <li class="active">
                                <?php else: ?>
                                <li>
                                <?php endif ?>
                                    <a href="/">Главная</a>
                                </li>
                                <?php if (null != $this->_registry->session->character): ?>
                                <?php if ('world' == $this->_registry->router->getController()): ?>
                                <li class="dropdown active">
                                <?php else: ?>
                                <li class="dropdown">
                                <?php endif ?>
                                    <a href="/world" class="dropdown-toggle"
                                       data-toggle="dropdown" data-target="#">
                                        Игра
                                        <b class="caret"></b>
                                    </a>

                                    <ul class="dropdown-menu">
                                        <li>
                                            <a href="/world">
                                                Мир
                                            </a>
                                        </li>
                                        <li>
                                            <a href="/world/inventory">
                                                Инвентарь
                                            </a>
                                        </li>
                                    </ul>
                                </li>
                                <?php endif ?>
                                <li>
                                    <a href="#">
                                        База знаний
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        Форум
                                    </a>
                                </li>
                                <?php if (null != $this->_registry->session->user): ?>
                                <li>
                                    <a href="/auth/logout">
                                        Выход
                                    </a>
                                </li>
                                <?php endif ?>
                            </ul>
                        </div>
                    </div>

                    <div class="row">
                        <div class="span10">
                            <?php echo $this->content() ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Форма выбора персонажа -->
        <div id="characters-list" class="hide">
            Ваши персонажи:
            <ul id="characters-list">
            </ul>
        </div>
    </body>
</html>
